### ISSUE TITLE
Bug: walls disappear

### ISSUE THREAD

**Issue by quintenvandamme** [tsoding/koil#41]
When running koil i found a bug when looking at a specific direction. Also wall collision still works.

https://github.com/user-attachments/assets/58409a68-209f-44b3-bf7d-1ee239a74845

**Comment by quintenvandamme** [comment]
There is no error in the console:
![image](https://github.com/user-attachments/assets/12bba9b2-fcb5-4ad9-b3ac-8e916ff64cb3)

**Comment by rexim** [comment]
Huh, it actually looks surprisingly similar to #39 Probably the same root cause. I'll look into that, thanks!

**Comment by rexim** [comment]
Should be fixed by ad6d011ac017bd2292f89766de4d72f2dc59ec05

**Comment by quintenvandamme** [comment]
seems to be fixed
