### ISSUE TITLE
Utilize vectors here

### ISSUE THREAD

**Issue by achiya-SX** [tsoding/koil#42]
https://github.com/tsoding/koil/blob/43fd65b29dce9c3d81122f23698b21fac9874280/client.c3#L129

I think there is a missed opportunity here to use built-in vectors for mult

**Comment by rexim** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by rexim** [comment]
Minor refactoring suggestions as per [CONTRIBUTING.md](https://github.com/tsoding/koil/blob/89d18ff54a01c3a11d29d61288fb3608f606b949/CONTRIBUTING.md) are not considered, since I have limited resources to maintain my projects.
